version: "3"

services:
  datastore:
    image: singularities/datastore-emulator
    environment:
      - DATASTORE_PROJECT_ID=dsui-local
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081
    ports:
      - 8081:8081

  datastore-ui:
    image: skarpdev:datastore-ui
    environment:
      DSUI_PROJECT_ID: dsui-local
      DSUI_PORT: 8282
      DSUI_DATASTORE_ENDPOINT: datastore:8081
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 8282:8282
    depends_on:
      - datastore
    links:
      - datastore
